dependencies:
- name: conference-agenda
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.25
- name: conference-sponsors
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.21
- name: conference-site
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.19
