dependencies:
- name: "conference-agenda"
  repository: "http://chartmuseum.jenkins-x.io"
  version: "0.0.4"
- name: "conference-sponsors"
  repository: "http://chartmuseum.jenkins-x.io"
  version: "0.0.4"
