dependencies:
- name: conference-agenda
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.21
- name: conference-sponsors
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.18
- name: conference-site
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.10
