dependencies:
- name: "conference-agenda"
  repository: "https://storage.googleapis.com/chartmuseum.jenkins-x.io"
  version: "0.0.4"
- name: "conference-sponsors"
  repository: "https://storage.googleapis.com/chartmuseum.jenkins-x.io"
  version: "0.0.4"
